extends: C:\Users\dwhieb\Coding\dev\.eslintrc
parserOptions:
  ecmaVersion: 8
env:
  browser: true
  node: true
globals:
  Handlebars: true
  lingRef: true
rules:
  camelcase: off
  require-jsdoc: off
  valid-jsdoc: off
